routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('levels', 'LevelController');

Route::resource('categories', 'CategoryController');

Route::resource('institutes', 'InstituteController');

Route::resource('courses', 'CourseController');

Route::get('courses/modules/{id}', 'CourseController@course')->name('course.module');

Route::resource('modules', 'ModuleController');

Route::resource('photos', 'PhotoController');

resources/views/courses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'courses.store']) !!}

                        @include('courses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/courses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($course, ['route' => ['courses.update', $course->id], 'method' => 'patch']) !!}

                        @include('courses.fields')

                   {!! Form::close() !!}
               </div>
               
           </div>
       </div>
   </div>
@endsection

resources/views/courses/fields.blade.php
<!-- Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('code', 'Code:') !!}
    {!! Form::text('code', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control', 'rows' => 3]) !!}
</div>

<!-- Duration Field -->
<div class="form-group col-sm-6">
    {!! Form::label('duration', 'Duration:') !!}
    {!! Form::text('duration', null, ['class' => 'form-control']) !!}
</div>

<!-- Institute Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('institute_id', 'Select Institute:') !!}
    {!!Form::select('institute_id', $institutes->pluck('name', 'id'), null, ['class' => 'form-control'])!!}
</div>

<!-- Category Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category_id', 'Select Category:') !!}
    {!!Form::select('category_id', $categories->pluck('name', 'id'), null, ['class' => 'form-control'])!!}
</div>

<!-- Level Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('level_id', 'Select Level:') !!}
    {!!Form::select('level_id', $levels->pluck('name', 'id'), null, ['class' => 'form-control'])!!}
</div>

<!-- Mqa Level Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mqa_level', 'Mqa Level:') !!}
    {!! Form::text('mqa_level', null, ['class' => 'form-control']) !!}
</div>

<!-- Fee Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fee', 'Fee:') !!}
    {!! Form::text('fee', null, ['class' => 'form-control']) !!}
</div>

<!-- Requirement Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('requirement', 'Requirement:') !!}
    {!! Form::textarea('requirement', null, ['class' => 'form-control', 'rows' => 3]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('courses.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Courses</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('courses.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('courses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/courses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('courses.show_fields')
                </div>
                <div class="row">
                   <div class="col-md-6">
                       <h3>Modules</h3>
                   </div>
                   <div class="col-md-6">
                        <a href="{!! route('course.module', [$course->id]) !!}" class="btn btn-default pull-right">Add Module</a>
                   </div>
                   <div class="col-md-12">
                        <ul class="list-group">
                            @forelse ($course->modules as $module)
                                <li class="list-group-item">{{ $module->name}} ({{ $module->code}})</li>
                            @empty
                                <li class="list-group-item">No module found</li>
                            @endforelse
                        </ul>
                   </div>
                    
               </div>
               <div class="row">
                   <div class="col-md-12">
                       <a href="{!! route('courses.index') !!}" class="btn btn-default">Back</a>
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection

resources/views/courses/show_fields.blade.php
<!-- Id Field -->
{{-- <div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $course->id !!}</p>
</div> --}}

<!-- Code Field -->
<div class="form-group">
    {!! Form::label('code', 'Code:') !!}
    <p>{!! $course->code !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $course->name !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $course->description !!}</p>
</div>

<!-- Duration Field -->
<div class="form-group">
    {!! Form::label('duration', 'Duration:') !!}
    <p>{!! $course->duration !!}</p>
</div>

<!-- Institute Id Field -->
<div class="form-group">
    {!! Form::label('institute_id', 'Institute Id:') !!}
    <p>{!! $course->institute->name !!}</p>
</div>

<!-- Category Id Field -->
<div class="form-group">
    {!! Form::label('category_id', 'Category Id:') !!}
    <p>{!! $course->category->name !!}</p>
</div>

<!-- Level Id Field -->
<div class="form-group">
    {!! Form::label('level_id', 'Level Id:') !!}
    <p>{!! $course->level->name !!}</p>
</div>

<!-- Mqa Level Field -->
<div class="form-group">
    {!! Form::label('mqa_level', 'Mqa Level:') !!}
    <p>{!! $course->mqa_level !!}</p>
</div>

<!-- Fee Field -->
<div class="form-group">
    {!! Form::label('fee', 'Fee:') !!}
    <p>{!! $course->fee !!}</p>
</div>

<!-- Requirement Field -->
<div class="form-group">
    {!! Form::label('requirement', 'Requirement:') !!}
    <p>{!! $course->requirement !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! \Carbon\Carbon::parse($course->created_at)->format('d MM Y')!!}</p>
</div>

<!-- Updated At Field -->
{{-- <div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $course->updated_at !!}</p>
</div> --}}

resources/views/courses/table.blade.php
<table class="table table-responsive" id="courses-table">
    <thead>
        <tr>
            <th>Code</th>
        <th>Name</th>
        {{-- <th>Description</th> --}}
        <th>Duration</th>
        <th>Institute</th>
        <th>Category</th>
        <th>Level</th>
        <th>Mqa Level</th>
        <th>Fee</th>
        {{-- <th>Requirement</th>
            <th colspan="3">Action</th>
        </tr> --}}
    </thead>
    <tbody>
    @foreach($courses as $course)
        <tr>
            <td>{!! $course->code !!}</td>
            <td>{!! $course->name !!}</td>
            {{-- <td>{!! $course->description !!}</td> --}}
            <td>{!! $course->duration !!}</td>
            <td>{!! $course->institute->name !!}</td>
            <td>{!! $course->category->name !!}</td>
            <td>{!! $course->level->name !!}</td>
            <td>{!! $course->mqa_level !!}</td>
            <td>{!! $course->fee !!}</td>
            {{-- <td>{!! $course->requirement !!}</td> --}}
            <td>
                {!! Form::open(['route' => ['courses.destroy', $course->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('courses.show', [$course->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('courses.edit', [$course->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>